export enum Authority {
    SYS_ADMIN = 'SYS_ADMIN',
    TENANT_ADMIN = 'TENANT_ADMIN',
    CUSTOMER_ADMIN = 'CUSTOMER_ADMIN',
    CUSTOMER_USER = 'CUSTOMER_USER',
    TENANT_USER = 'TENANT_USER',
    REFRESH_TOKEN = 'REFRESH_TOKEN',
    ANONYMOUS = 'ANONYMOUS'
}
